// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Folder struct {
	ID             int32
	Name           string
	Description    sql.NullString
	ParentFolderID sql.NullInt32
	CreatedAt      sql.NullTime
}

type Note struct {
	ID        int32
	FolderID  sql.NullInt32
	Title     string
	Body      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
